
name: cont_int

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          
      - name: Run tests
        run: pytest --cov=life_expectancy
        
      - name: Run pylint
        run: |
          pylint life_expectancy.main
          pylint life_expectancy.load
          pylint life_expectancy.clean
          pylint life_expectancy.region
          pylint life_expectancy.tests.conftest
          pylint life_expectancy.tests.test_cleaning
          pylint life_expectancy.tests.test_load_save
          pylint life_expectancy.tests.test_main
          pylint life_expectancy.tests.test_region
